# Generated by Django 2.1.7 on 2019-02-25 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phonesetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='statsession',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='button',
            old_name='buttonName',
            new_name='button_name',
        ),
    ]
