# Generated by Django 2.1.7 on 2019-02-25 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phonesetup', '0002_auto_20190225_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='statactivity',
            fields=[
                ('activity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('button_file_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('button_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonesetup.button')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonesetup.statsession')),
            ],
        ),
    ]
