# Generated by Django 2.1.7 on 2019-02-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonesetup', '0003_statactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statsession',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
